COUNTRY_CODE_CONSTANT = {'28': 'Botswana', '212': 'Tonga', '96': 'Hong Kong', '255': 'Palau',
                         '43': 'Chile', '253': 'Jersey Island', '121': 'Libyan Arab Jamahiriya',
                         '81': 'Germany', '101': 'Iran (Islamic Republic of)', '5': 'Andorra',
                         '214': 'Tunisia', '33': 'Bulgaria', '115': 'Kyrgyzstan', '132': 'Malta',
                         '192': 'Somalia', '68': 'Ethiopia', '55': 'Cyprus', '220': 'Ukraine',
                         '76': 'French Polynesia', '54': 'Cuba', '93': 'Haiti', '25': 'Bhutan',
                         '144': 'Morocco', '139': 'Micronesia, Federated States of', '91': 'Guinea-bissau',
                         '230': 'Viet Nam', '65': 'Equatorial Guinea', '195': 'Spain',
                         '60': 'Dominican Republic', '147': 'Namibia', '9': 'Antigua and Barbuda',
                         '129': 'Malaysia', '167': 'Peru', '137': 'Mayotte', '133': 'Marshall Islands',
                         '50': 'Cook Islands', '238': 'Zambia', '173': 'Qatar', '71': 'Fiji', '155': 'Niger',
                         '208': 'Tanzania, United Republic of', '241': 'Macedonia', '12': 'Aruba',
                         '226': 'Uzbekistan', '52': "Cote D'Ivoire", '40': 'Cayman Islands', '30': 'Brazil',
                         '166': 'Paraguay', '88': 'Guam', '200': 'Suriname', '190': 'Slovenia', '2': 'Albania',
                         '114': 'Kuwait', '231': 'Virgin Islands (British)', '78': 'Gabon', '100': 'Indonesia',
                         '225': 'Uruguay', '213': 'Trinidad and Tobago', '18': 'Bangladesh', '204': 'Switzerland',
                         '237': 'Zaire', '31': 'British Indian Ocean Territory', '105': 'Italy', '1': 'Afghanistan',
                         '142': 'Mongolia', '26': 'Bolivia', '168': 'Philippines', '162': 'Pakistan',
                         '36': 'Cambodia', '210': 'Togo', '123': 'Lithuania', '189': 'Slovakia (Slovak Republic)',
                         '95': 'Honduras', '254': 'Saint Pierre and Miquelon', '113': 'Korea, Republic of',
                         '169': 'Pitcairn', '150': 'Netherlands', '83': 'Gibraltar', '39': 'Cape Verde',
                         '29': 'Bouvet Island', '22': 'Belize', '86': 'Grenada', '175': 'Romania',
                         '119': 'Lesotho', '62': 'Ecuador', '47': 'Colombia', '159': 'Northern Mariana Islands',
                         '176': 'Russian Federation', '19': 'Barbados', '127': 'Madagascar', '170': 'Poland',
                         '80': 'Georgia', '194': 'South Georgia and the South Sandwich Islands', '89': 'Guatemala',
                         '131': 'Mali', '27': 'Bosnia and Herzegovina', '64': 'El Salvador', '109': 'Kazakhstan',
                         '72': 'Finland', '102': 'Iraq', '145': 'Mozambique', '197': 'St. Helena', '174': 'Reunion',
                         '219': 'Uganda', '32': 'Brunei Darussalam', '82': 'Ghana', '97': 'Hungary', '20': 'Belarus',
                         '199': 'Sudan', '98': 'Iceland', '85': 'Greenland', '75': 'French Guiana',
                         '4': 'American Samoa', '34': 'Burkina Faso', '161': 'Oman', '103': 'Ireland',
                         '90': 'Guinea', '117': 'Latvia', '99': 'India', '152': 'New Caledonia', '177': 'Rwanda',
                         '24': 'Bermuda', '41': 'Central African Republic', '227': 'Vanuatu', '84': 'Greece',
                         '156': 'Nigeria', '154': 'Nicaragua', '116': "Lao People's Democratic Republic",
                         '223': 'United States', '63': 'Egypt', '202': 'Swaziland', '222': 'United Kingdom',
                         '198': 'St. Pierre and Miquelon', '224': 'United States Minor Outlying Islands',
                         '187': 'Sierra Leone', '122': 'Liechtenstein', '46': 'Cocos (Keeling) Islands',
                         '87': 'Guadeloupe', '128': 'Malawi', '207': 'Tajikistan', '70': 'Faroe Islands',
                         '196': 'Sri Lanka', '171': 'Portugal', '125': 'Macau', '7': 'Anguilla', '51': 'Costa Rica',
                         '11': 'Armenia', '193': 'South Africa', '42': 'Chad', '107': 'Japan', '15': 'Azerbaijan',
                         '111': 'Kiribati', '35': 'Burundi', '135': 'Mauritania', '120': 'Liberia', '13': 'Australia',
                         '179': 'Saint Lucia', '69': 'Falkland Islands (Malvinas)', '229': 'Venezuela',
                         '77': 'French Southern Territories', '209': 'Thailand', '221': 'United Arab Emirates',
                         '158': 'Norfolk Island', '215': 'Turkey', '240': 'Serbia', '3': 'Algeria',
                         '140': 'Moldova, Republic of', '110': 'Kenya', '151': 'Netherlands Antilles',
                         '243': 'Montenegro', '149': 'Nepal', '94': 'Heard and Mc Donald Islands', '104': 'Israel',
                         '178': 'Saint Kitts and Nevis', '218': 'Tuvalu', '205': 'Syrian Arab Republic',
                         '49': 'Congo', '130': 'Maldives', '48': 'Comoros', '233': 'Wallis and Futuna Islands',
                         '153': 'New Zealand', '61': 'East Timor', '228': 'Vatican City State (Holy See)',
                         '79': 'Gambia', '182': 'San Marino', '165': 'Papua New Guinea', '146': 'Myanmar',
                         '134': 'Martinique', '181': 'Samoa', '112': "Korea, Democratic People's Republic of",
                         '203': 'Sweden', '164': 'Panama', '92': 'Guyana', '245': 'Croatia', '106': 'Jamaica',
                         '8': 'Antarctica', '14': 'Austria', '66': 'Eritrea', '201': 'Svalbard and Jan Mayen Islands',
                         '59': 'Dominica', '124': 'Luxembourg', '185': 'Senegal', '10': 'Argentina',
                         '118': 'Lebanon', '184': 'Saudi Arabia', '157': 'Niue', '191': 'Solomon Islands',
                         '17': 'Bahrain', '136': 'Mauritius', '16': 'Bahamas', '141': 'Monaco', '57': 'Denmark',
                         '239': 'Zimbabwe', '250': 'Guernsey', '23': 'Benin', '160': 'Norway', '216': 'Turkmenistan',
                         '172': 'Puerto Rico', '211': 'Tokelau', '38': 'Canada', '183': 'Sao Tome and Principe',
                         '148': 'Nauru', '37': 'Cameroon', '232': 'Virgin Islands (U.S.)', '143': 'Montserrat',
                         '6': 'Angola', '138': 'Mexico', '186': 'Seychelles', '217': 'Turks and Caicos Islands',
                         '108': 'Jordan', '58': 'Djibouti', '73': 'France', '206': 'Taiwan', '21': 'Belgium',
                         '67': 'Estonia', '188': 'Singapore', '180': 'Saint Vincent and the Grenadines',
                         '234': 'Western Sahara', '56': 'Czech Republic'}
